services:
  - type: web
    name: oddsmtaani
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers=2 --threads=4 --timeout=30 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PORT
        value: 5000
